---
plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  DisplayCopNames: true

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false
